name: Build and Deploy Vue App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Vue App
        run: npm run build

      - name: Copy Build Artifacts to Another Repository
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Another Repository
        uses: actions/checkout@v2
        with:
          repository: chulminz/vue-dist

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Commit Changes
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          git config --global user.email "chulminz@gmail.com"
          git config --global user.name "Cheolmin Hwang"
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git add .
          git commit -m "Update dist folder"
          git push git@github.com:chulminz/vue-dist.git
